In [1]:
import numpy as np

In [2]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [3]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [4]:
arr1.flatten() #Convert any multi-dimensional array into a 1D array. It returns a copy of the original array collapsed into one dimension.

array([2, 2, 2, 2, 1, 1, 1, 1, 1], dtype=int32)

In [5]:
#Expanding dimensions
arr=np.array([1,2,3,4])

In [6]:
arr.ndim

1

In [7]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1, 2, 3, 4]])

In [8]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1],
       [2],
       [3],
       [4]])

In [9]:
np.expand_dims(arr,axis=1).ndim

2

In [10]:
arr=np.zeros((3,4))

In [11]:
arr.ndim #Number of dimensions in the array

2

In [12]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [13]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [14]:
np.expand_dims(arr,axis=0).ndim

3

In [15]:
np.expand_dims(arr,axis=1).ndim

3

In [16]:
a=np.array([[1],[2],[3]])

In [17]:
a

array([[1],
       [2],
       [3]])

In [18]:
a.ndim

2

In [19]:
np.squeeze(a) #Remove single-dimensional entries from the shape of an array. It returns a new array with the same data but with all the dimensions of size 1 removed.

array([1, 2, 3])

In [20]:
np.squeeze(a).ndim

1

In [21]:
np.repeat(a,4) #Repeat elements of an array. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter.

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [22]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [23]:
np.repeat(arr1,2)

array([2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [24]:
np.repeat(arr1,2,axis=0) #Repeat elements of an array along a specified axis. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter, and the axis along which to repeat is specified by the 'axis' parameter.

array([[2, 2, 2],
       [2, 2, 2],
       [2, 1, 1],
       [2, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [25]:
np.repeat(arr1,2,axis=1) #Repeat elements of an array along a specified axis. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter, and the axis along which to repeat is specified by the 'axis' parameter.

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]], dtype=int32)

In [26]:
a

array([[1],
       [2],
       [3]])

In [27]:
np.roll(a,-2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[3],
       [1],
       [2]])

In [28]:
np.roll(a,-1) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[2],
       [3],
       [1]])

In [29]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [30]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [31]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [32]:
np.roll(c,-2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [33]:
np.roll(c,2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [34]:
np.roll(a,2,axis=0) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[2],
       [3],
       [1]])

In [35]:
np.roll(c,2,axis=1) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [36]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [37]:
arr2

array([[2, 2, 1],
       [2, 1, 1],
       [1, 2, 2]], dtype=int32)

In [38]:
arr1+arr2

array([[4, 4, 3],
       [4, 2, 2],
       [2, 3, 3]], dtype=int32)

In [39]:
arr1-arr2

array([[ 0,  0,  1],
       [ 0,  0,  0],
       [ 0, -1, -1]], dtype=int32)

In [40]:
arr1*arr2

array([[4, 4, 2],
       [4, 1, 1],
       [1, 2, 2]], dtype=int32)

In [41]:
arr1>arr2

array([[False, False,  True],
       [False, False, False],
       [False, False, False]])

In [42]:
~arr1 #Bitwise NOT of an array. It returns a new array with the bitwise NOT of each element in the input array. The bitwise NOT operation flips the bits of the binary representation of each element, resulting in a new value where all bits are inverted (0s become 1s and 1s become 0s).

array([[-3, -3, -3],
       [-3, -2, -2],
       [-2, -2, -2]], dtype=int32)

In [43]:
#Operations on Numpy String Array

d=np.array(['hello','world','python','numpy'])

In [44]:
d

array(['hello', 'world', 'python', 'numpy'], dtype='<U6')

In [45]:
np.char.upper(d) #Convert each element of the array to uppercase. It returns a new array with the same shape as the input array, but with all the characters in each element converted to uppercase.

array(['HELLO', 'WORLD', 'PYTHON', 'NUMPY'], dtype='<U6')

In [46]:
np.char.capitalize(d) #Capitalize the first character of each element in the array. It returns a new array with the same shape as the input array, but with the first character of each element converted to uppercase and the rest of the characters converted to lowercase.

array(['Hello', 'World', 'Python', 'Numpy'], dtype='<U6')

In [47]:
#Mathematical operations on Numpy 

In [48]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [49]:
np.sin(arr1) #Calculate the trigonometric sine of each element in the input array. It returns a new array with the same shape as the input array, but with the sine of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the sine of the corresponding element in the input array.

array([[0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.84147098, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [50]:
np.cos(arr1) #Calculate the trigonometric cosine of each element in the input array. It returns a new array with the same shape as the input array, but with the cosine of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the cosine of the corresponding element in the input array.

array([[-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684,  0.54030231,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [51]:
np.tan(arr1) #Calculate the trigonometric tangent of each element in the input array. It returns a new array with the same shape as the input array, but with the tangent of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the tangent of the corresponding element in the input array.

array([[-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986,  1.55740772,  1.55740772],
       [ 1.55740772,  1.55740772,  1.55740772]])

In [52]:
np.log10(arr1) #Calculate the natural logarithm of each element in the input array. It returns a new array with the same shape as the input array, but with the natural logarithm of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the natural logarithm of the corresponding element in the input array. Note that the natural logarithm is only defined for positive real numbers, so if any element in the input array is zero or negative, the output will contain NaN (Not a Number) or -inf (negative infinity) values.

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.     , 0.     ],
       [0.     , 0.     , 0.     ]])

In [53]:
np.exp(arr1) #Calculate the exponential of each element in the input array. It returns a new array with the same shape as the input array, but with the exponential of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the exponential of the corresponding element in the input array.

array([[7.3890561 , 7.3890561 , 7.3890561 ],
       [7.3890561 , 2.71828183, 2.71828183],
       [2.71828183, 2.71828183, 2.71828183]])

In [54]:
np.power(arr1,3) #Calculate the power of each element in the input array to the specified exponent. It returns a new array with the same shape as the input array, but with each element raised to the power of the specified exponent. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the result of raising the corresponding element in the input array to the specified exponent.

array([[8, 8, 8],
       [8, 1, 1],
       [1, 1, 1]], dtype=int32)

In [55]:
np.mean(arr1) #Calculate the arithmetic mean of the elements in the input array. It returns a single value which is the average of all the elements in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the mean of the elements in the input array.

np.float64(1.4444444444444444)

In [56]:
np.max(arr1) #Calculate the maximum value of the elements in the input array. It returns a single value which is the largest element in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the maximum element in the input array.

np.int32(2)

In [57]:
np.min(arr1) #Calculate the minimum value of the elements in the input array. It returns a single value which is the smallest element in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the minimum element in the input array.

np.int32(1)

In [58]:
np.std(arr1) #Calculate the standard deviation of the elements in the input array. It returns a single value which is the standard deviation of all the elements in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the standard deviation of the elements in the input array.

np.float64(0.4969039949999533)

In [59]:
np.var(arr1) #Calculate the variance of the elements in the input array. It returns a single value which is the variance of all the elements in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the variance of the elements in the input array.

np.float64(0.2469135802469136)

In [60]:
arr1-arr2

array([[ 0,  0,  1],
       [ 0,  0,  0],
       [ 0, -1, -1]], dtype=int32)

In [61]:
np.subtract(arr1,arr2) #Subtract elements of the second array from the first array. It returns a new array with the same shape as the input arrays, where each element is the result of subtracting the corresponding element in the second array from the corresponding element in the first array. The input arrays must have the same shape or be broadcastable to a common shape. The output will be a new array containing the differences between the corresponding elements of the input arrays.

array([[ 0,  0,  1],
       [ 0,  0,  0],
       [ 0, -1, -1]], dtype=int32)

In [62]:
arr1*arr2

array([[4, 4, 2],
       [4, 1, 1],
       [1, 2, 2]], dtype=int32)

In [63]:
np.multiply(arr1,arr2) #Element-wise multiplication of two arrays. It returns a new array with the same shape as the input arrays, where each element is the product of the corresponding elements in the input arrays. The input arrays must have the same shape or be broadcastable to a common shape.

array([[4, 4, 2],
       [4, 1, 1],
       [1, 2, 2]], dtype=int32)

In [64]:
np.mod(arr1,arr2) #Calculate the element-wise remainder of the division of the first array by the second array. It returns a new array with the same shape as the input arrays, where each element is the result of the modulus operation between the corresponding elements in the input arrays. The input arrays must have the same shape or be broadcastable to a common shape. The output will be a new array containing the remainders of the division of the corresponding elements in the input arrays.

array([[0, 0, 0],
       [0, 0, 0],
       [0, 1, 1]], dtype=int32)

In [65]:
np.sqrt(arr1) #Calculate the non-negative square root of each element in the input array. It returns a new array with the same shape as the input array, but with the square root of each element calculated. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where each element is the non-negative square root of the corresponding element in the input array. Note that if any element in the input array is negative, the output will contain NaN (Not a Number) values for those elements, since the square root of a negative number is not defined in the real number system.

array([[1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.        , 1.        ],
       [1.        , 1.        , 1.        ]])

In [66]:
#Sort Search

e=np.array([5,6,1,2,3,4])

In [67]:
e

array([5, 6, 1, 2, 3, 4])

In [68]:
np.sort(e) #Return a sorted copy of an array. It returns a new array with the same shape as the input array, but with the elements sorted in ascending order. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where the elements are sorted in ascending order.

array([1, 2, 3, 4, 5, 6])

In [69]:
f=np.array([5,199,200,6,7,8])

In [70]:
f

array([  5, 199, 200,   6,   7,   8])

In [71]:
np.sort(f) #Return a sorted copy of an array. It returns a new array with the same shape as the input array, but with the elements sorted in ascending order. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where the elements are sorted in ascending order.

array([  5,   6,   7,   8, 199, 200])

In [72]:
np.searchsorted(f,170) #Find indices where elements should be inserted to maintain order. It returns an array of indices where the specified values should be inserted in the input array to maintain the sorted order. The input array must be sorted in ascending order. The output will be an array of indices corresponding to the positions where the specified values should be inserted in the input array. 

np.int64(6)

In [73]:
arr1

array([[2, 2, 2],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [74]:
f=np.array([5,199,200,6,7,8,0,0,0,0,])

In [75]:
f

array([  5, 199, 200,   6,   7,   8,   0,   0,   0,   0])

In [76]:
np.count_nonzero(f) #Count the number of non-zero elements in the input array. It returns a single value which is the count of non-zero elements in the array. The input array can be of any shape and can contain real or complex numbers. The output will be a single value representing the number of non-zero elements in the input array.

np.int64(6)

In [77]:
f[f>0] #Return the elements of the input array that satisfy the specified condition. It returns a new array containing only the elements from the input array that are greater than zero. The input array can be of any shape and can contain real or complex numbers. The output will be a new array containing only the elements from the input array that are greater than zero.

array([  5, 199, 200,   6,   7,   8])

In [78]:
np.where(f>0) #Return the indices of the elements in the input array that satisfy the specified condition. It returns a tuple of arrays, where each array contains the indices of the elements in the input array that satisfy the condition. The input array can be of any shape and can contain real or complex numbers. The output will be a tuple of arrays containing the indices of the elements in the input array that are greater than zero.

(array([0, 1, 2, 3, 4, 5]),)

In [79]:
np.extract(f>0,f) #Return the elements of the input array that satisfy the specified condition. It returns a new array containing only the elements from the input array that satisfy the condition. The input array can be of any shape and can contain real or complex numbers. The output will be a new array containing only the elements from the input array that satisfy the condition. The first argument is a boolean array that specifies the condition, and the second argument is the input array from which to extract the elements.

array([  5, 199, 200,   6,   7,   8])

In [80]:
f

array([  5, 199, 200,   6,   7,   8,   0,   0,   0,   0])

In [81]:
f.byteswap() #Return a new array with the bytes of the elements swapped. It returns a new array with the same shape and data type as the input array, but with the bytes of each element swapped. The input array can be of any shape and can contain real or complex numbers. The output will be a new array where the bytes of each element are swapped, which can be useful for changing the endianness of the data or for performing certain types of data manipulation.

array([  360287970189639680, -4107282860161892352, -4035225266123964416,
         432345564227567616,   504403158265495552,   576460752303423488,
                          0,                    0,                    0,
                          0])

In [ ]:
#Matrices >> 2D array

import numpy.matlib as nm #The numpy.matlib module provides functions for working with matrices in NumPy. It includes functions for creating matrices, performing matrix operations, and manipulating matrix data. The module is designed to provide a convenient interface for working with matrices, which are a specific type of 2D array in NumPy.

In [83]:
np.zeros(5) #Return a new array of given shape and type, filled with zeros. It returns a new array with the specified shape and data type, where all elements are initialized to zero. The input can be a single integer (for a 1D array) or a tuple of integers (for multi-dimensional arrays). The output will be a new array filled with zeros.

array([0., 0., 0., 0., 0.])

In [85]:
np.ones((3,4)) #Return a new array of given shape and type, filled with ones. It returns a new array with the specified shape and data type, where all elements are initialized to one. The input can be a single integer (for a 1D array) or a tuple of integers (for multi-dimensional arrays). The output will be a new array filled with ones.  

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])