In [2]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [5]:
arr1.flatten() #Convert any multi-dimensional array into a 1D array. It returns a copy of the original array collapsed into one dimension.

array([2, 1, 1, 1, 1, 2, 1, 2, 2], dtype=int32)

In [6]:
#Expanding dimensions
arr=np.array([1,2,3,4])

In [7]:
arr.ndim

1

In [8]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr,axis=1).ndim

2

In [11]:
arr=np.zeros((3,4))

In [12]:
arr.ndim #Number of dimensions in the array

2

In [13]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr,axis=0).ndim

3

In [16]:
np.expand_dims(arr,axis=1).ndim

3