In [2]:
import numpy as np

In [4]:
q=np.zeros(5)

In [6]:
q

array([0., 0., 0., 0., 0.])

In [7]:
b=np.zeros((3,4)) #3 rows and 4 columns

In [8]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
b.ndim

2

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [14]:
arr=np.zeros((3,4))  #3 rows and 4 columns of zeros

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr.ndim

2

In [17]:
#3 dimensional array
arr=np.zeros((1,3,4))  #1 block, 3 rows and 4 columns of zeros

In [18]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [20]:
np.zeros((1,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
arr=np.zeros((1,2,3,4))  #1 cube, 2 blocks, 3 rows and 4 columns of zeros

In [22]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [23]:
arr.ndim

4

In [24]:
arr=np.ones((3,4))

In [25]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
arr.ndim

2

In [27]:
arr.shape

(3, 4)

In [28]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [30]:
arr+5 #adding 5 to each element

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [31]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [32]:
arr-1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.eye(3) #returs a 2-d array with 1s on the diagonal and 0s elsewhere >> identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [43]:
np.empty((2,3)) #return a new array of given shape and type, without initializing entries

array([[6.23042070e-307, 1.24109290e-320, 0.00000000e+000],
       [1.04857643e-311, 0.00000000e+000, 7.56571287e-307]])

In [ ]:
#optional >>> random module >>> 

import random
random.choice((1,2,3,4,5))

5

In [47]:
random.choice("Pashupati")

'i'

In [46]:
random.choice(["apple","banana","cherry"])  

'banana'

In [50]:
random.randrange(1,1000) #returns a randomly selected element from range(start, stop) 

143

In [51]:
random.random() #returns a random float number between 0.0 to 1.0 >> o is inclusive and 1 is exclusive

0.9883489495025406

In [52]:
list=[1,2,3,4,5,6,7,8,9,10]

In [53]:
random.shuffle(list)  #shuffles the sequence x in place

In [55]:
list

[3, 8, 10, 2, 4, 9, 5, 6, 7, 1]

In [56]:
random.uniform(7,14)  #returns a random float number between the two given numbers

13.375370445577705

#Generate random numbers with numpy array

In [58]:
#random number related concept in numpy
np.array([])

array([], dtype=float64)

In [59]:
np.random.random_sample()

0.5054027846632414

In [61]:
np.random.random_sample((3,4))  #3 rows and 4 columns of random float numbers between 0.0 to 1.0

array([[0.51974741, 0.8972016 , 0.76688742, 0.58357893],
       [0.07364063, 0.81783724, 0.35041363, 0.96446882],
       [0.65835386, 0.67660042, 0.94421169, 0.90387544]])

In [63]:
np.random.rand((1)) 

array([0.85814894])

In [ ]:
np.random.randn(2,3) #2 rows and 3 columns of array of random numbers from standard normal distribution

array([[-0.52031009,  0.21103747,  1.47780727],
       [ 1.94798472,  0.94277525, -1.85522841]])

In [66]:
arr=np.random.randint(1,5,size=(3,4))  #3 rows and 4 columns of random integers between 1 to 5 (5 is exclusive  )

In [67]:
arr

array([[1, 2, 2, 2],
       [1, 2, 3, 2],
       [3, 2, 2, 1]], dtype=int32)

In [68]:
arr.ndim

2

In [69]:
arr.shape

(3, 4)

In [70]:
arr.size

12

In [71]:
arr

array([[1, 2, 2, 2],
       [1, 2, 3, 2],
       [3, 2, 2, 1]], dtype=int32)

In [72]:
#reshaping the array

arr.reshape(2,6)

array([[1, 2, 2, 2, 1, 2],
       [3, 2, 3, 2, 2, 1]], dtype=int32)

In [73]:
arr.shape

(3, 4)

In [74]:
arr.size

12

In [75]:
#Array size will remain same after reshaping >> always reshape parameter should be multiplication of original array size