In [1]:
import numpy as np

In [3]:
q=np.zeros(5)

In [4]:
q

array([0., 0., 0., 0., 0.])

In [5]:
b=np.zeros((3,4)) #3 rows and 4 columns

In [6]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [7]:
b.ndim

2

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [10]:
arr=np.zeros((3,4))  #3 rows and 4 columns of zeros

In [11]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [12]:
arr.ndim

2

In [13]:
#3 dimensional array
arr=np.zeros((1,3,4))  #1 block, 3 rows and 4 columns of zeros

In [14]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [33]:
np.zeros((1,3,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [30]:
arr=np.zeros((1,2,3,4),dtype=int)  #1 cube, 2 blocks, 3 rows and 4 columns of zeros

In [31]:
arr

array([[[[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]],

        [[0, 0, 0, 0],
         [0, 0, 0, 0],
         [0, 0, 0, 0]]]])

In [18]:
arr.ndim

4

In [28]:
arr=np.ones((3,4),dtype=int)

In [29]:
arr

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [21]:
arr.ndim

2

In [22]:
arr.shape

(3, 4)

In [23]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [24]:
arr+5 #adding 5 to each element

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [25]:
arr*5

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [26]:
arr-1

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [36]:
np.eye(3) #returs a 2-d array with 1s on the diagonal and 0s elsewhere >> identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [37]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [38]:
np.empty((2,3)) #return a new array of given shape and type, without initializing entries

array([[9.34577196e-307, 9.34598246e-307, 1.60218491e-306],
       [1.69119873e-306, 1.24611673e-306, 1.05699581e-307]])

In [60]:
#optional >>> random module >>> 

import random
random.choice((1,2,3,4,5))

4

In [47]:
random.choice("Pashupati")

'i'

In [46]:
random.choice(["apple","banana","cherry"])  

'banana'

In [54]:
random.choice(["Head","Tail"])

'Head'

In [43]:
random.randrange(1,1000) #returns a randomly selected element from range(start, stop) 

288

In [61]:
random.random() #returns a random float number between 0.0 to 1.0 >> o is inclusive and 1 is exclusive

0.7429005721315158

In [62]:
list=[1,2,3,4,5,6,7,8,9,10]

In [63]:
random.shuffle(list)  #shuffles the sequence x in place

In [64]:
list

[5, 3, 10, 2, 4, 9, 6, 1, 7, 8]

In [65]:
random.uniform(7,14)  #returns a random float number between the two given numbers

12.558600863057286

#Generate random numbers with numpy array

In [66]:
#random number related concept in numpy
np.array([])

array([], dtype=float64)

In [67]:
np.random.random_sample()

0.9716492191554342

In [68]:
np.random.random_sample((3,4))  #3 rows and 4 columns of random float numbers between 0.0 to 1.0

array([[0.4214671 , 0.99039193, 0.66480517, 0.78319742],
       [0.98557176, 0.77886435, 0.46598618, 0.24159649],
       [0.32467041, 0.1891755 , 0.19752091, 0.76172148]])

In [71]:
np.random.rand((1)) #To generate a random number between 0 and 1

array([0.94669964])

In [ ]:
np.random.randn(2,3)
 #Here we get float numbers from the standard normal distribution. The first argument is the number of rows and the second argument is the number of columns. So, we get a 2D array with 2 rows and 3 columns of random numbers from the standard normal distribution.
 #2 rows and 3 columns of array of random numbers from standard normal distribution

array([[-0.24148874,  0.44309564,  0.28148103],
       [-0.92019658, -0.65655611,  0.36785956]])

In [72]:
arr=np.random.randint(1,5,size=(3,4))  #3 rows and 4 columns of random integers between 1 to 5 (5 is exclusive  )

In [73]:
arr

array([[4, 1, 2, 1],
       [1, 4, 2, 4],
       [3, 1, 1, 1]], dtype=int32)

In [74]:
arr.ndim

2

In [75]:
arr.shape

(3, 4)

In [76]:
arr.size

12

In [77]:
arr

array([[4, 1, 2, 1],
       [1, 4, 2, 4],
       [3, 1, 1, 1]], dtype=int32)

In [78]:
#reshaping the array

arr.reshape(2,6)

array([[4, 1, 2, 1, 1, 4],
       [2, 4, 3, 1, 1, 1]], dtype=int32)

In [79]:
arr.shape

(3, 4)

In [80]:
arr.size

12

In [81]:
#Array size will remain same after reshaping >> always reshape parameter should be multiplication of original array size

In [82]:
#case when we dont know in reshape what should be the column count

arr.reshape(4,-1) 

array([[4, 1, 2],
       [1, 1, 4],
       [2, 4, 3],
       [1, 1, 1]], dtype=int32)

In [83]:
arr.reshape(2,-1) # Reshapes the array to 2 rows and automatically calculates the number of columns

array([[4, 1, 2, 1, 1, 4],
       [2, 4, 3, 1, 1, 1]], dtype=int32)

In [84]:
#you dont know row count
arr.reshape(-1,3) # Reshapes the array to 3 columns and automatically calculates the number of rows

array([[4, 1, 2],
       [1, 1, 4],
       [2, 4, 3],
       [1, 1, 1]], dtype=int32)

In [86]:
arr.size

12

In [87]:
#To see original array after reshaping
arr.reshape(12,1).base

array([[4, 1, 2, 1],
       [1, 4, 2, 4],
       [3, 1, 1, 1]], dtype=int32)

In [88]:
arr.reshape(2,2,3)

array([[[4, 1, 2],
        [1, 1, 4]],

       [[2, 4, 3],
        [1, 1, 1]]], dtype=int32)

In [90]:
arr.reshape(1,2,2,3) #Reshapes the array to 1 block, 2 rows, 2 columns and 1 depth
#In layman terms, we are reshaping the array to have 1 block, 2 rows, 2 columns and 1 depth. So, we get a 4D array with 1 block, 2 rows, 2 columns and 1 depth.

array([[[[4, 1, 2],
         [1, 1, 4]],

        [[2, 4, 3],
         [1, 1, 1]]]], dtype=int32)

In [91]:
arr.reshape(1,2,2,3).base

array([[4, 1, 2, 1],
       [1, 4, 2, 4],
       [3, 1, 1, 1]], dtype=int32)

In [94]:
arr.reshape(1,2,2,3).ndim

4

In [95]:
arr.reshape(4,3,1) #3 rows and 1 column repeated 4 times to make 4 blocks of 3 rows and 1 column


array([[[4],
        [1],
        [2]],

       [[1],
        [1],
        [4]],

       [[2],
        [4],
        [3]],

       [[1],
        [1],
        [1]]], dtype=int32)

In [96]:
#Conditions on Array

arr=np.random.randint(1,10,(5,6)) #5 rows and 6 columns of random integers between 1 to 10 (10 is exclusive)

In [97]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [98]:
arr.shape

(5, 6)

In [99]:
arr.ndim

2

In [100]:
arr.size

30

In [ ]:
arr>3 #returns a boolean array of the same shape as arr, where each element is True if the corresponding element in arr is greater than 3, and False otherwise.

array([[ True,  True, False,  True, False,  True],
       [ True, False, False,  True,  True, False],
       [ True,  True,  True, False,  True,  True],
       [False,  True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True,  True]])

In [102]:
arr[arr>3] #returns a 1D array containing only the elements of arr that are greater than 3. The resulting array will have a shape that depends on the number of elements in arr that satisfy the condition arr > 3.

array([4, 8, 7, 4, 4, 4, 8, 4, 4, 4, 7, 6, 9, 7, 5, 6, 7, 4, 5, 5, 7, 4],
      dtype=int32)

In [103]:
arr[arr<3] #returns a 1D array containing only the elements of arr that are less than 3. The resulting array will have a shape that depends on the number of elements in arr that satisfy the condition arr < 3.

array([1, 2, 2, 2, 1, 2, 2], dtype=int32)

In [ ]:
#To access specific rows and columns in the array
#To accesss element at specific row and column, we can use the indexing operator [].
arr[0] #returns the first row of the array arr. The resulting array will have a shape that depends on the number of columns in arr.

array([4, 8, 1, 7, 2, 4], dtype=int32)

In [105]:
arr[1] #returns the second row of the array arr. The resulting array will have a shape that depends on the number of columns in arr.

array([4, 2, 3, 4, 8, 2], dtype=int32)

In [107]:
arr[1][0] #returns the first element of the second row of the array arr. The resulting value will be a single integer, which is the element located at the first column of the second row in arr.

np.int32(4)

In [109]:
arr[0:2] #returns the first two rows of the array arr. The resulting array will have a shape that depends on the number of columns in arr.

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2]], dtype=int32)

In [112]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [110]:
arr[0:3,[0,2]] #returns a 2D array containing the first three rows and the first and third columns of arr. The resulting array will have a shape that depends on the number of rows and columns in arr that satisfy the specified indices.

array([[4, 1],
       [4, 3],
       [4, 4]], dtype=int32)

In [113]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [111]:
#Slicing on both rows and Column
arr[0:2,1:3] #returns a 2D array containing the first two rows and the second and third columns of arr. The resulting array will have a shape that depends on the number of rows and columns in arr that satisfy the specified indices.

array([[8, 1],
       [2, 3]], dtype=int32)

In [115]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [114]:
arr[0:2,[0,1]] #returns a 2D array containing the first two rows and the first and second columns of arr. The resulting array will have a shape that depends on the number of rows and columns in arr that satisfy the specified indices.

array([[4, 8],
       [4, 2]], dtype=int32)

In [116]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [117]:
arr[0,[1,2]] #returns a 1D array containing the elements from the first row of arr at the second and third columns. The resulting array will have a shape that depends on the number of columns in arr that satisfy the specified indices.

array([8, 1], dtype=int32)

In [119]:
arr

array([[4, 8, 1, 7, 2, 4],
       [4, 2, 3, 4, 8, 2],
       [4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [ ]:
arr[2:4,[0,3]] #returns a 2D array containing the third and fourth rows and the first and fourth columns of arr. The resulting array will have a shape that depends on the number of rows and columns in arr that satisfy the specified indices.

array([[4, 1],
       [2, 5]], dtype=int32)

In [121]:
arr[2:5] #returns the third, fourth and fifth rows of the array arr. The resulting array will have a shape that depends on the number of columns in arr.

array([[4, 4, 4, 1, 7, 6],
       [2, 9, 7, 5, 6, 7],
       [4, 2, 5, 5, 7, 4]], dtype=int32)

In [122]:
arr[2:5,0:2] #returns a 2D array containing the third, fourth and fifth rows and the first and second columns of arr. The resulting array will have a shape that depends on the number of rows and columns in arr that satisfy the specified indices.

array([[4, 4],
       [2, 9],
       [4, 2]], dtype=int32)

In [ ]:
#Mathematical operations on arrays
arr1=np.random.randint(1,3,size=(3,3)) #3 rows and 3 columns of random integers between 1 to 3 (3 is exclusive)
arr2=np.random.randint(1,3,size=(3,3)) #3 rows and 3 columns of random integers between 1 to 3 (3 is exclusive)

In [132]:
arr1

array([[1, 1, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [133]:
arr2

array([[1, 2, 1],
       [2, 1, 1],
       [1, 1, 1]], dtype=int32)

In [134]:
arr1+arr2 #returns a new array where each element is the sum of the corresponding elements from arr1 and arr2. The resulting array will have the same shape as arr1 and arr2, which is (3, 3) in this case. Each element in the resulting array will be the sum of the corresponding elements from arr1 and arr2.

array([[2, 3, 3],
       [3, 3, 3],
       [2, 3, 3]], dtype=int32)