In [2]:
import numpy as np

In [4]:
q=np.zeros(5)

In [6]:
q

array([0., 0., 0., 0., 0.])

In [7]:
b=np.zeros((3,4)) #3 rows and 4 columns

In [8]:
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
b.ndim

2

In [10]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [11]:
np.array([[2,2,2],[2,2,2]])

array([[2, 2, 2],
       [2, 2, 2]])

In [14]:
arr=np.zeros((3,4))  #3 rows and 4 columns of zeros

In [15]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
arr.ndim

2

In [17]:
#3 dimensional array
arr=np.zeros((1,3,4))  #1 block, 3 rows and 4 columns of zeros

In [18]:
arr

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])