In [2]:
import numpy as np

In [3]:
arr1=np.random.randint(1,3,(3,3))
arr2=np.random.randint(1,3,(3,3))

In [4]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [5]:
arr1.flatten() #Convert any multi-dimensional array into a 1D array. It returns a copy of the original array collapsed into one dimension.

array([2, 1, 1, 1, 1, 2, 1, 2, 2], dtype=int32)

In [6]:
#Expanding dimensions
arr=np.array([1,2,3,4])

In [7]:
arr.ndim

1

In [8]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1, 2, 3, 4]])

In [9]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[1],
       [2],
       [3],
       [4]])

In [10]:
np.expand_dims(arr,axis=1).ndim

2

In [11]:
arr=np.zeros((3,4))

In [12]:
arr.ndim #Number of dimensions in the array

2

In [13]:
np.expand_dims(arr,axis=0) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [14]:
np.expand_dims(arr,axis=1) #Expand the shape of an array by inserting a new axis at the specified position. It returns a new array with the same data but with an additional dimension.

array([[[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]],

       [[0., 0., 0., 0.]]])

In [15]:
np.expand_dims(arr,axis=0).ndim

3

In [16]:
np.expand_dims(arr,axis=1).ndim

3

In [17]:
a=np.array([[1],[2],[3]])

In [18]:
a

array([[1],
       [2],
       [3]])

In [19]:
a.ndim

2

In [20]:
np.squeeze(a) #Remove single-dimensional entries from the shape of an array. It returns a new array with the same data but with all the dimensions of size 1 removed.

array([1, 2, 3])

In [21]:
np.squeeze(a).ndim

1

In [22]:
np.repeat(a,4) #Repeat elements of an array. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter.

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [23]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [24]:
np.repeat(arr1,2)

array([2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 2, 2, 2, 2], dtype=int32)

In [25]:
np.repeat(arr1,2,axis=0) #Repeat elements of an array along a specified axis. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter, and the axis along which to repeat is specified by the 'axis' parameter.

array([[2, 1, 1],
       [2, 1, 1],
       [1, 1, 2],
       [1, 1, 2],
       [1, 2, 2],
       [1, 2, 2]], dtype=int32)

In [26]:
np.repeat(arr1,2,axis=1) #Repeat elements of an array along a specified axis. It returns a new array which contains the repeated values. The number of repetitions for each element is specified by the 'repeats' parameter, and the axis along which to repeat is specified by the 'axis' parameter.

array([[2, 2, 1, 1, 1, 1],
       [1, 1, 1, 1, 2, 2],
       [1, 1, 2, 2, 2, 2]], dtype=int32)

In [27]:
a

array([[1],
       [2],
       [3]])

In [28]:
np.roll(a,-2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[3],
       [1],
       [2]])

In [29]:
np.roll(a,-1) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[2],
       [3],
       [1]])

In [30]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
c=np.array([[1,2],[3,4],[5,6],[7,8]])

In [32]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [33]:
np.roll(c,-2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [34]:
np.roll(c,2) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[7, 8],
       [1, 2],
       [3, 4],
       [5, 6]])

In [35]:
np.roll(a,2,axis=0) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[2],
       [3],
       [1]])

In [36]:
np.roll(c,2,axis=1) #Roll array elements along a specified axis. It returns a new array with the same shape as the input array, but with the elements shifted by the specified number of positions. The elements that are rolled beyond the last position are re-introduced at the first position.

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [37]:
arr1

array([[2, 1, 1],
       [1, 1, 2],
       [1, 2, 2]], dtype=int32)

In [38]:
arr2

array([[1, 2, 1],
       [1, 1, 2],
       [2, 2, 1]], dtype=int32)

In [39]:
arr1+arr2

array([[3, 3, 2],
       [2, 2, 4],
       [3, 4, 3]], dtype=int32)

In [40]:
arr1-arr2

array([[ 1, -1,  0],
       [ 0,  0,  0],
       [-1,  0,  1]], dtype=int32)

In [41]:
arr1*arr2

array([[2, 2, 1],
       [1, 1, 4],
       [2, 4, 2]], dtype=int32)

In [42]:
arr1>arr2

array([[ True, False, False],
       [False, False, False],
       [False, False,  True]])

In [43]:
~arr1 #Bitwise NOT of an array. It returns a new array with the bitwise NOT of each element in the input array. The bitwise NOT operation flips the bits of the binary representation of each element, resulting in a new value where all bits are inverted (0s become 1s and 1s become 0s).

array([[-3, -2, -2],
       [-2, -2, -3],
       [-2, -3, -3]], dtype=int32)

In [ ]:
#Operations on Numpy String Array
