![Process](Process.png)

Numpy means Numerical Python

In [4]:
#numpy >>> numerical python
#2005 by Travis Oliphant
#library for numerical computations in python

In [5]:
pip install numpy

^C
Note: you may need to restart the kernel to use updated packages.


   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 989.2 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.3 MB 987.4 kB/s eta 0:00:12
   -- ------------------------------------- 0.8/12.3 MB 987.4 kB/s eta 0:00:12
   --- ------------------------------------ 1.0/12.3 MB 986.7 kB/s eta 0:00:12
   ---- ----------------------------------- 1.3/12.3 MB 1.0 MB/s eta 0:00:11
   ----- ---------------------------------- 1.6/12.3 MB 932.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/12.3 MB 932.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.6/12.3 MB 932.2 kB/s eta 0:00:12
   ----- ---------------------------------- 1.8/12.3 MB 812.0 kB/s eta 0:00:13
   ----- ---------------------------------- 1.8/12.3 MB 812.0 kB/s eta 0:00:13
  

In [6]:
import numpy as np

In [7]:
np.__version__

'2.4.1'

In [8]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [1]:
list1=[1,2,3,4,"Pashupati"]

In [2]:
type(list1)

list

In [ ]:
#Numpy stores the data in an array
#An array is a container used to store the data of same type

In [4]:
#Why Numpy?
#Computation is Fast >> due to array >> contiguous memory allocation
#mathematical computations


In [5]:
l=[1,2,3,4,5]

In [8]:
import numpy as np
array=np.array(l)


In [9]:
array

array([1, 2, 3, 4, 5])

In [10]:
l=[1,2,3,4,5.1]
array=np.array(l)

In [11]:
array

array([1. , 2. , 3. , 4. , 5.1])

In [12]:
l=[1,2,3,4,5.1,"Pashupati"]
array=np.array(l)

In [13]:
array

array(['1', '2', '3', '4', '5.1', 'Pashupati'], dtype='<U32')

In [14]:
#array stores homogeneous data

In [15]:
type(array)

numpy.ndarray

In [18]:
array.ndim

1

In [19]:
array1=np.array([[1,2,3],[4,5,6]]) #2D array

In [20]:
array1

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
#number of square brackets = number of dimensions

In [22]:
array1.ndim

2

In [24]:
mat=np.matrix([1,2,3,4,5]) #matrix is a specialized array of 2 dimension always

In [25]:
type(mat)

numpy.matrix

In [ ]:
np.matrix([[[1,2],[3,4],[5,6],[7,8]]]) #through an error
#matrix cannot be more than 2D

In [27]:
#more way to construct array
li=[1,2,3]
np.asarray(li)

array([1, 2, 3])

In [ ]:
mat